import { Box, Flex,Text } from '@chakra-ui/react'
import Head from 'next/head'
import styles from "../styles/Home.module.css"


export default function Home() {
  return (
    <>
      <Head>
        <title>Expense Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box mt={"10"} mx={["5%","5%","10%","30%"]} p={["5","3","7","9"]} border='1px' borderColor='gray.200'>
        <Flex  direction="column">
        <Box>
          <Text color="#9E9C9C" fontSize="md">Good Morning!</Text>
          <Text ml={"5"} fontSize="lg">Muhammad Hasaan</Text>
        </Box>

        <Box className={styles.card} m={"1"} border="1px">
         <Text fontSize={'3xl'}>$ Amount</Text>
         <div className={`${styles.outerCircle} ${styles.bordergradientpurple}`}>

         </div>
        </Box>
        </Flex>
        </Box>
    </>
  )
}
